load semantics-basics-narrowing.maude
load semantics-bitvector-gen.maude

fmod BIT-FVP is
	protecting BOOL-FVP * (
		sort Bool to BitFVP,
		op true to 1,
		op false to 0
	) .
	protecting BOOL-FVP * (
		sort Bool to BoolFVP,
		op true to tt,
		op false to ff
	) .

	sort BitVFVP .
	subsort BitFVP < BitVFVP .

	op emptyBV : -> BitVFVP [ctor] .
	op __ : BitVFVP BitVFVP -> BitVFVP [ctor assoc id: emptyBV prec 10] .

	op _and_ : BitVFVP BitVFVP -> BitVFVP [ditto] . *** Revise, should be ctor?
	op _or_ : BitVFVP BitVFVP -> BitVFVP [ctor ditto] .
	op _xor_ : BitVFVP BitVFVP -> BitVFVP [ditto] .
	op not_ : BitVFVP -> BitVFVP [ditto] .

    op _=_ : BitFVP BitFVP -> BoolFVP .
    op _/=_ : BitFVP BitFVP -> BoolFVP .
	op _<_ : BitFVP BitFVP -> BoolFVP .
    op _<=_ : BitFVP BitFVP -> BoolFVP .
    op _>_ : BitFVP BitFVP -> BoolFVP .
    op _>=_ : BitFVP BitFVP -> BoolFVP .
	
	vars X Y : BitVFVP .
	vars A B : BitFVP .

	*** TODO: Should include [owise] in corresponding cases (if any)?
	eq X 0 or Y 0 = (X or Y) 0 [variant] .
	eq X A or Y 1 = (X or Y) 1 [variant] .
	eq X 1 or Y B = (X or Y) 1 [variant] .
	eq emptyBV or Y = Y [variant] .
	eq X or emptyBV = X [variant] .

	eq X 1 and Y 1 = (X and Y) 1 [variant] .
	eq X A and Y 0 = (X and Y) 0 [variant] .
	eq emptyBV and Y = 0 [variant] .
	eq X and emptyBV = 0 [variant] .

	eq X A xor Y A = (X xor Y) 0 [variant] .
	eq X 0 xor Y 1 = (X xor Y) 1 [variant] .
	eq X 1 xor Y 0 = (X xor Y) 1 [variant] .
	eq emptyBV xor Y = Y [variant] .
	eq X xor emptyBV = X [variant] .

	eq not X 0 = (not X) 1 [variant] .
	eq not X 1 = (not X) 0 [variant] .
	eq not emptyBV = 1 [variant] .

	***Maude> vu-narrow in BIT-FVP : (1 p:BitVFVP) or (1 0 0) =>! 1 1 q:BitFVP 1 .
	***Solution 1
	***rewrites: 28 in 3ms cpu (2ms real) (9333 rewrites/second)
	***state: 1 #1:BitVFVP or 1 0 0
	***accumulated substitution:
	***p:BitVFVP --> #1:BitVFVP
	***variant unifier:
	***q:BitFVP --> 0
	***#1:BitVFVP --> %1:BitFVP 0 1
***
	***Solution 2
	***rewrites: 28 in 3ms cpu (2ms real) (9333 rewrites/second)
	***state: 1 #1:BitVFVP or 1 0 0
	***accumulated substitution:
	***p:BitVFVP --> #1:BitVFVP
	***variant unifier:
	***q:BitFVP --> 1
	***#1:BitVFVP --> %1:BitFVP 1 1

	eq (A = A) = tt [variant] .
    eq (A = B) = ff [owise variant] .
    eq (A /= B) = not (A = B) [variant] .
    eq (0 < 1) = tt [variant] .
    eq (A < B) = ff [owise variant] .
    eq (0 <= B) = tt [variant] .
    eq (A <= B) = ff [owise variant] .
    eq (1 > 0) = tt [variant] .
    eq (A > B) = ff [owise variant] .
    eq (1 >= B) = tt [variant] .
    eq (A >= B) = ff [owise variant] .

endfm

view BitFVP from TRIV to BIT-FVP is
  sort Elt to BitFVP .
endv
view BitVFVP from TRIV to BIT-FVP is
  sort Elt to BitVFVP .
endv

fmod BIT-NRW-CONVERSION is
	pr BIT .
    pr BIT-FVP .

    op toBitVFVP : BitV -> BitVFVP [metadata "convF"] .

    var Bit       : Bit .
    var BitV      : BitV .

	eq toBitVFVP(emptyBV) = (emptyBV).BitFVP .
	eq toBitVFVP((0).Bit) = (0).BitFVP .
    eq toBitVFVP((1).Bit) = (1).BitFVP .
    ***eq toBitVFVP(BitV Bit) = toBitVFVP(BitV) toBitVFVP(Bit) [owise] .
    eq toBitVFVP((0).Bit BitV) = toBitVFVP((0).Bit) toBitVFVP(BitV) [owise] .
    eq toBitVFVP((1).Bit BitV) = toBitVFVP((1).Bit) toBitVFVP(BitV) [owise] .
endfm

***fmod TEST is
***
***	pr META-LEVEL .
***	pr BIT-NRW-CONVERSION .
***
***endfm