load ../semantics-basics/semantics-basics.maude

fmod WHILE-LANG-INSTS-MOD is

    protecting CONCRETE-FW-NORAT .

    sort Inst .

    op skip ; : -> Inst [ctor prec 20] .
    op _ := _ ; : IVar IExp -> Inst [ctor prec 20] .
    op _ := _ ; : BVar BExp -> Inst [ctor prec 20] .

endfm

view Inst from TRIV to WHILE-LANG-INSTS-MOD is
  sort Elt to Inst .
endv

fmod WHILE-LANG-BLOCK-MOD is

    protecting WHILE-LANG-INSTS-MOD .
    protecting LIST{Inst} * (sort List{Inst} to Program) .

    op if _ then {_} else {_} : BExp Program Program -> Inst [ctor prec 20] .
    op if _ then {_} : BExp Program -> Inst [prec 20] .

    op while _ do {_} : BExp Program -> Inst [ctor prec 20] .

    var B : BExp .
    var P1 : Program .

    eq if B then {P1} = if B then {P1} else {nil} .

endfm

fmod WHILE-BASICS is
    protecting WHILE-LANG-BLOCK-MOD .
endfm

mod WHILE-MAUDE is

    protecting WHILE-BASICS .

    sort State .
    
    op < _ | _ > : Program Stores -> State [ctor] . 
    op errState : -> State [ctor] . 

    vars Var Var1 Var2 : Var .
    var IVar : IVar .
    var BVar : BVar .
    vars BExp BExp2 : BExp .
    vars P P1 P2 : Program .
    vars STR STR2 : Stores .
    var ISTR : IStore .
    var BSTR : BStore .
    var IExp : IExp .
    var Q : Qid .

    op start : Program -> State .
    eq start(P) = < P | ((empty).IStore | (empty).BStore) > .

    rl [skip] : 
        < skip ; P | STR >
        =>
        < P | STR > .

    rl [assign-I] : 
        < iv(Q) := IExp ; P | (ISTR | BSTR) >
        =>
        < P | insert(Q, eval(IExp, ISTR), ISTR) | BSTR > .

    rl [assign-B] : 
        < bv(Q) := BExp ; P | (ISTR | BSTR) >
        =>
        < P | ISTR | insert(Q, eval(BExp, (ISTR | BSTR)), BSTR) > .

    crl [if-then] : 
        < if BExp then { P1 } else { P2 } P | STR >
        =>
        < P1 P | STR >
        if eval(BExp, STR) .

    crl [if-else] : 
        < if BExp then { P1 } else { P2 } P | STR >
        =>
        < P2 P | STR >
        if not eval(BExp, STR) .

    crl [while-loop] : 
        < while BExp do { P1 } P | STR >
        =>
        < P1 while BExp do { P1 } P | STR >
        if eval(BExp, STR) .
        
    crl [while-exit] : 
        < while BExp do { P1 } P | STR >
        =>
        < P | STR >
        if not eval(BExp, STR) .

    *** Auxiliary

    op getStore : State -> Stores .
    eq getStore(< P | STR >) = STR .

    op updateStore : State Stores -> State .
    eq updateStore(< P | STR >, STR2) = < P | STR2 > .

endm

mod EXAMPLE is

    protecting WHILE-MAUDE .

	ops ex1 ex2 : -> Program .

	eq ex1 = if iv('x) > val(1)
	                 then { iv('x) := iv('x) + val(3) ; }
	                 else { iv('x) := val(7) ; } .

	eq ex2 = if iv('x) > val(0)
					then { iv('x) := iv('x) ; }
					else { iv('x) := - iv('x) ; } .
endm