***
*** Example of symbolic execution by narrowing
***

load ../semantics-basics/semantics-basics-narrowing.maude

mod SYMBOLIC-EXECUTION-NARROWING is
	protecting INT-FVP * (
		sort Bool to BoolFVP,
		sort Int to IntFVP,
		sort Nat to NatFVP,
		sort NzNat to NzNatFVP,
		op true to tt,
		op false to ff
	) .
	protecting NAT .
	protecting QID .

	sorts AExp BExp .

	*** Logic and arithmetic expressions (more logic operators
	*** could be defined, but not integer product)

	op ivar : Qid -> AExp [ctor] .
	op ival : Nat -> AExp [ctor] .
	op bval : Bool -> BExp [ctor] .
	op _+_ : AExp AExp -> AExp [ctor] .
	op _-_ : AExp AExp -> AExp [ctor] .
	op -_ : AExp -> AExp [ctor] .
	op _>_ : AExp AExp -> BExp [ctor] .
	op _and_ : BExp BExp -> BExp [ctor] .
	op not_ : BExp -> BExp [ctor] .

	var  ISTR       : IStore .
	var  N          : Nat .
	vars AE AE1 AE2 : AExp .
	vars BE BE1 BE2 : BExp .
	vars NF NF1     : IntFVP .
	vars Q Q'       : Qid .
	vars P1 P2 P3   : Program .

	*** Integer variable store (for simplicity,
	*** we do not define other variable stores)
	sort IStore .

	op none : -> IStore [ctor] .
	op _|->_ : Qid IntFVP -> IStore [ctor] .
	op _;_ : IStore IStore -> IStore [ctor assoc comm id: none prec 50] .

	op store : Qid IntFVP IStore -> IStore .

	eq store(Q, NF, none) = Q |-> NF .
	eq store(Q, NF, Q |-> NF1 ; ISTR) = Q |-> NF ; ISTR .
	eq store(Q, NF, Q' |-> NF1 ; ISTR) = Q' |-> NF1 ; store(Q, NF, ISTR) .

	*** Evaluation functions

	op eval : AExp IStore -> IntFVP .
	op eval : BExp IStore -> BoolFVP .

	eq eval(ivar(Q), Q |-> NF ; ISTR) = NF .
	eq eval(ival(0), ISTR) = 0 .
	eq eval(ival(s N), ISTR) = 1 + eval(ival(N), ISTR) .
	eq eval(AE1 + AE2, ISTR) = eval(AE1, ISTR) + eval(AE2, ISTR) .
	eq eval(AE1 - AE2, ISTR) = eval(AE1, ISTR) - eval(AE2, ISTR) .
	eq eval(- AE, ISTR) = - eval(AE, ISTR) .

	eq eval(bval(true), ISTR) = tt .
	eq eval(bval(false), ISTR) = ff .
	eq eval(AE1 > AE2, ISTR) = eval(AE1, ISTR) > eval(AE2, ISTR) .
	eq eval(BE1 and BE2, ISTR) = eval(BE1, ISTR) and eval(BE2, ISTR) .
	eq eval(not BE, ISTR) = not eval(BE, ISTR) .

	*** Programs
	sort Program .

	op if _ then {_} else {_} : BExp Program Program -> Program [ctor] .  *** condicional
	op _:=_ : Qid AExp -> Program [ctor] .  *** asignación

	op skip : -> Program [ctor] .
	op _;_ : Program Program -> Program [ctor assoc prec 50] .

	eq P1 ; skip = P1 [variant] . *** needed for narrowing

	*** Exucution state (and auxiliary extension)
	sort State .

	op <_,_>   : Program IStore -> State [ctor] .
	op <_,_,_> : Program IStore BoolFVP -> State [ctor] .

	*** Semantic rules

	*** Each rule L => R if eval(...) = C is translated to
	*** L => < L, eval(...) > y < L, C > => R (narrowing as
	*** implemented in Maude is unconditional and topmost)

	rl [ifpre] :
		< if BE then { P1 } else { P2 } ; P3, ISTR >
	=>
		< if BE then { P1 } else { P2 } ; P3, ISTR, eval(BE, ISTR) >
	[narrowing] .

	rl [ifthen] :
		< if BE then { P1 } else { P2 } ; P3, ISTR, tt >
	=>
		< P1 ; P3, ISTR >
	[narrowing] .

	rl [ifelse] :
		< if BE then { P1 } else { P2 } ; P3, ISTR, ff >
	=>
		< P2 ; P3, ISTR >
	[narrowing] .

	rl [assign] :
		< (Q := AE) ; P3, ISTR >
	=>
		< P3, store(Q, eval(AE, ISTR), ISTR) >
	[narrowing] .
endm

mod EXAMPLE is
	protecting SYMBOLIC-EXECUTION-NARROWING .

	ops ex1 ex2 : -> Program .

	eq ex1 = if ivar('x) > ival(1)
	                 then { 'x := ivar('x) + ival(3) }
	                 else { 'x := ival(7) } .

	eq ex2 = if ivar('x) > ival(0)
					then { 'x := ivar('x) }
					else { 'x := - ivar('x) } .

	*** To be used as < ex1, 'x |-> X:IntFVP > .

	var S    : State .
	var ISTR : IStore .
	var NF   : NatFVP .
	var IF   : IntFVP .
endm

eof

*** Reachable finite states
*** (fold or vfold can be used, but substitutions are lost)
*** (path can be used to retrieve the execution path)
vu-narrow {delay, filter} < ex1, 'x |-> X:NatFVP > =>+ < skip, ISTR > .

*** Property: the result is no 7 seven greater than X
vu-narrow {delay, filter} < ex1, 'x |-> X:NatFVP > =>+ < skip, 'x |-> 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + X:NatFVP > .

*** Property: the result is positive
vu-narrow {delay, filter} < ex2, 'x |-> X:IntFVP > =>+ < skip, 'x |-> - Y:NzNatFVP > .

*** Preimages of the result (Y and - Y)
vu-narrow {delay, filter} < ex2, 'x |-> X:IntFVP > =>+ < skip, 'x |-> Y:NzNatFVP > .
